### ISSUE TITLE
What is the popularity criterion for publishing a package in this repo?

### ISSUE THREAD

**Issue by aykutkardas** [enaqx/awesome-react#1351]
> Sure, I plan to clean this list and left only well established popular components. You can add to https://github.com/brillout/awesome-react-component which is longer list of components.

_Originally posted by @enaqx in https://github.com/enaqx/awesome-react/issues/1189#issuecomment-1517931416_
            

A package with 16k downloads per week was rejected.
![image](https://user-images.githubusercontent.com/7966133/233699823-a579b9b8-ec24-46c6-b1b5-8105e9218c94.png)

**Comment by enaqx** [comment]
@aykutkardas Please use https://github.com/brillout/awesome-react-component since it is more suitable list for your component. It is opinionated list -  that is criteria.

I tend to remove all project which has pages like this https://icomoon.io/#premium
I just focus on free and opensource things.

Here is motivation in Contribution https://github.com/enaqx/awesome-react#contribution

As you can see for git history I spend time on **significant** cleanup of this list since it became ridiculous for real usage.

**Comment by aykutkardas** [comment]
In fact, [react-icomoon](https://github.com/aykutkardas/react-icomoon) is associated with the following project, which is also open source and contains more than 40,000 icons.

https://svgps.app/

I respect your decision. Thanks for the explanation.
